In [7]:
#np.insert(array,index,value,asix= none)
#axis = 0 row 1 col
import numpy as np
arr1d = np.array((1,2,3,4,5,6))
print(arr1d)
new_arr = np.insert(arr1d,2,25)
print(new_arr)

[1 2 3 4 5 6]
[ 1  2 25  3  4  5  6]


In [15]:
import numpy as np
arr2d = np.array([[1,2],[3,4]])
new_arr = np.insert(arr2d,1,[5,6],axis=0)
print(new_arr)

new_arr = np.insert(arr2d,1,[5,6],axis=1)
print(new_arr)

arr = np.array((10,20,30,40,50))
arrn =np.append(arr,[123,345])
print(arrn)
#print(arr.append([10,20,90]))

[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]
[ 10  20  30  40  50 123 345]
