In [5]:
#Cocatenate
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([45,78,88])
arr3 = np.concatenate((arr1,arr2))
print(arr3)
#remove
arr4= np.delete(arr1,0)
print(arr1)
print(arr4)

arr_2d = np.array([[1,2,3],[4,5,6]])
arr2dnew = np.delete(arr_2d,0,axis=0)
print(arr_2d)
print(arr2dnew)

[ 1  2  3 45 78 88]
[1 2 3]
[2 3]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
