In [3]:
import numpy as np

arr = np.array([1.2,1.6,7.8,8.9])

arr_int = arr.astype(int)
print(arr_int)
print(arr_int.dtype)
arr12 = np.array((1,2,3,4,5,6))
print(arr12)

[1 1 7 8]
int64
[1 2 3 4 5 6]


In [2]:
arr =np.array([1,2,3,4])
print(arr)

[1 2 3 4]
