In [4]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr[::])
print(arr[::2])
print(arr[::-1])

[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


In [9]:
import numpy as np

arr3d = np.array([
    [(1,2,3,4,5), (6,7,8,9,10)],
    [(11,13,14,15,16), (17,18,19,20,21)]
])

arr3d[1:2:1]


array([[[11, 13, 14, 15, 16],
        [17, 18, 19, 20, 21]]])

In [11]:
import numpy as np
arr = np.array((1,2,34,5,6,6))
print(arr)
print(arr[arr>4])

[ 1  2 34  5  6  6]
[34  5  6  6]
